name: Update

on:
  repository_dispatch:
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    name: Update main
    strategy:
      fail-fast: false
      matrix:
        target: [main]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git wget git-core
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Clone
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b main https://github.com/liuran001/Magisk-Modules-Repo_Fast.git main
        cd main
        rm modules.json
        wget https://magisk-modules-repo.github.io/submission/modules.json
        sed -i 's#https://github.com/#https://hub.fastgit.org/gh/#g' ./modules.json
        

    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd $GITHUB_WORKSPACE/main
        git add .
        git commit -m "update$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --quiet "https://${{ secrets.TOKEN }}@github.com/liuran001/Magisk-Modules-Repo_Fast.git" HEAD:main
 

 
